### ISSUE TITLE
On Mac OS X Safari, clicking a marker shows "undefined" on the first click, the title on the second click.

### ISSUE THREAD

**Issue by sillygwailo** [jlord/hack-spots#6]
First click:

![screenshot 2013-08-16 01 45 33](https://f.cloud.github.com/assets/54067/974348/e5738a04-0650-11e3-81c2-9a9b9d4f4d4f.png)

Second click:

![screenshot 2013-08-16 01 45 39](https://f.cloud.github.com/assets/54067/974350/ec8478bc-0650-11e3-8e55-360670ff4495.png)

The same thing happens in iOS Safari. This does not happen in Chrome (at least not in Chrome Canary).

**Comment by jlord** [comment]
Ooo. Yeah, something is up, because I've seen somtimes in Chrome the first click does nothing and the second click works. Will look into it.

**Comment by NoahGordon** [comment]
Any update on this?

**Comment by jlord** [comment]
@NoahGordon Sorry, haven't had a chance to yet, planning on spending some time doing some sheetsee work in the next couple of weeks though before I do a session on it, so that'll be the fire under me :)

@jugglingnutcase mentioned in #11 that it may have to do with a missing mapbox.js interaction. Do you have any thoughts of where to look?

**Comment by jrsconfitto** [comment]
i'm so glad to hear that it's not just me seeing this. i've been meaning to go through the sheetsee js and make sure that i understand what it's doing. i'll take a :mag: if i think about it.

**Comment by jlord** [comment]
I think @jugglingnutcase fixed this with #12. YAY!

**Comment by jrsconfitto** [comment]
Yups :smile:
