### ISSUE TITLE
TypeError: geoJSON[0] is undefined

### ISSUE THREAD

**Issue by brandonrobertz** [jlord/hack-spots#7]
On FF 23.0.1, when hack-spots loads, it fails with the above error. I've tracked it back to gData being == [ ] and that seems to screw up the geoJSON var. I haven't tested this with any other browsers or versions yet.

I'll look more into this and see what I can't figure out.

**Comment by brandonrobertz** [comment]
It looks like Tabletop.init is handing a blank data object to the callback showInfo. This ruins everything.

**Comment by springmeyer** [comment]
It looks like an empty "Form Responses 1" table got added to the live spreadsheed and that is breaking tabletop. If you pass `debug:true` to tabletop it spits out:

```
Missing data for Form Responses 1, make sure you didn't forget column headers tabletop1.3.4.js:389
WARNING You have more than one sheet but are using simple sheet mode! Don't blame me when something goes wrong. tabletop1.3.4.js:389
Uncaught TypeError: Cannot read property 'properties' of undefined index.html:180
```

**Comment by jlord** [comment]
Dang! So, someone somewhere is doing something that adds that keeps adding other worksheet :confused:. I guess that's how my experiment in giving _everyone_ access goes :) I guess I can turn simple sheet off and just specify the name of the correct sheet since this will probably keep happening and I don't know how to find that person.

Thanks for doing the debug @springmeyer!

**Comment by jlord** [comment]
Ok, actually, what makes more sense is I create a new spreadsheet and update the links. Whoever has that thing set up, it then won't work anymore. So, I've done that and hopefully all stays working now! :)
